FROM golang:1.19-alpine3.16 as builder

RUN apk update && apk add --no-cache

RUN mkdir /app
WORKDIR /app

COPY go.mod .
COPY go.sum .

RUN go mod download

COPY payment /app/payment
COPY logger /app/logger

RUN cd /app/payment && CGO_ENABLED=0 GOOS=linux go build -a -installsuffix cgo -o payment .

ENTRYPOINT [ "./payment/payment" ]